apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-app-daemonset
  labels:
    app: my-app
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: ec-app
        image: akiranreddy/ec2
        ports:
        - containerPort: 80

