apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  volumes:
    - name: mysql-data
      emptyDir: {}
    - name: mysql-init
      configMap:
        name: mysql-init-script

  containers:
    - name: mysql
      image: mysql:5.7
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootpass
        - name: MYSQL_DATABASE
          value: appdb
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: mysql-init
          mountPath: /docker-entrypoint-initdb.d

    - name: mysql-dumper
      image: mysql:5.7
      env:
        - name: MYSQL_PWD
          value: rootpass
      command:
        - sh
        - -c
        - |
          until mysqladmin ping -h 127.0.0.1 -u root --silent; do
            echo "Waiting for MySQL...";
            sleep 5;
          done;
          while true; do
            echo "Dumping user table..."
            mysqldump -h 127.0.0.1 -u root appdb user > /var/lib/mysql/user_backup.sql
            sleep 60;
          done;
      volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql

