apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx
  nodeName: i-0c4e7640d41582ca5

#As node name is defined, we do not need a scheduler to handling the scheduling
#This is also know as manual scheduling/scaling

